### ISSUE TITLE
Provide sample rate limiting yaml

### ISSUE THREAD

**Issue by antiguru** [ashvina/streaming-samples#3]
Hi,
it would be great if the project contained a sample rate-limiting configuration. It's a bit tricky to reverse-engineer the structure from the source code.
Thank you!

**Comment by ashvina** [comment]
Sure, will add a sample in a bit. Thanks !

**Comment by ashvina** [comment]
@antiguru I have added a sample config file. Please let me know if you have any other questions. Thanks !

**Comment by antiguru** [comment]
Great, thank you!
